### ISSUE TITLE
change to python 3

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_nRF52_nrfutil#1]
@hathach does this have to be python 2 due to a dependancy? if it can be converted to python 3, then that would be good for long-term supportability!

**Comment by hathach** [comment]
yeah, we should either move to python 3 or going with a C port. The nrfutil mostly use serial port which should be easy to access from either language ( I am not really good with python :( ) 

https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/65

**Comment by hathach** [comment]
Ah thanks, I will try, but my Python knowledge is quite limited. Almost forgot everything every time I  got to work with Python :(

**Comment by ladyada** [comment]
not a problem. it should be all done so if you can test it and let me know if anything doesnt work that is best. i only tried dfu upload and genpkg!

**Comment by ladyada** [comment]
@hathach
