### ISSUE TITLE
Fatal Python error when running adafruit-nrfutil

### ISSUE THREAD

**Issue by boriswtam** [adafruit/Adafruit_nRF52_nrfutil#10]
I followed the instructions to install adafruit-nrfutil from source, but I have been getting the error: 

Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: unknown encoding: utf-8

Current thread 0x00007fffed06b3c0 (most recent call first):
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...82 completed.

I'm currently running MacOS 10.12 and am trying to program my NRF52840 Mini

**Comment by hathach** [comment]
For macos, please use either prebuilt binary or install it from pypi package.

**Comment by hathach** [comment]
closed due to lack of activities.
