### ISSUE TITLE
ModuleNotFoundError: No module named 'nordicsemi.__main__' - issue with latest pip install

### ISSUE THREAD

**Issue by JuggernautPanda** [adafruit/Adafruit_nRF52_nrfutil#17]
Hello. I recently updated the package and I am getting this error. It was working fine earlier.

Now I am unable to use the tool.

**Comment by JuggernautPanda** [comment]
adafruit-nrfutil version
Traceback (most recent call last):
  File "/usr/local/bin/adafruit-nrfutil", line 5, in <module>
    from nordicsemi.__main__ import cli
ModuleNotFoundError: No module named 'nordicsemi.__main__'

**Comment by JuggernautPanda** [comment]
OS: Ubuntu 18.04

**Comment by JuggernautPanda** [comment]
I got the issue. I tried to install nrfutil package as well.
 
This was causing the issue. I uninstalled both completely for both python3 and python2.7
sudo pip3 uninstall adafruit-nrfutil
sudo pip3 uninstall nrfutil
sudo pip uninstall adafruit-nrfutil
sudo pip uninstall nrfutil

Then I closed the terminal to open a new session and then reinstalled it by using
sudo pip3 install adafruit-nrfutil

**Comment by glorl** [comment]
Thank @JuggernautPanda, this solved the same problem for me

**Comment by artgodwin** [comment]
I tried to follow these instructions, but pip told me it was out of date and to update it.

After I updated it, every attempt to use pip fails with the error

1, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "~/.local/lib/python3.5/site-packages/pip/_internal/utils/entrypoints.py", line 12
    f"pip{sys.version_info.major}",
                                 ^

**Comment by hathach** [comment]
@artgodwin can you provide more info on your PC: device, OS version. Your python is pretty old 3.5, I think you probably need to update to later python version, or just use the old nrfutil that worked previously.

**Comment by dhalbert** [comment]
@hathach we took this to discord

**Comment by hathach** [comment]
thanks @dhalbert

**Comment by khimaros** [comment]
was there any solution?

**Comment by artgodwin** [comment]
I got it to work by running the whole Arduino IDE inside a python ve. I am
running the python 3 shipped with Debian. This obviously isn't a very good
solution and I think using python for build utilities is fairly risky : you
need to be very conservative unless you ship the appropriate version with
the BSP.

Ultimately I moved to the Nordic SDK instead of Arduino.
