### ISSUE TITLE
Windows COM times out

### ISSUE THREAD

**Issue by K2AAE** [adafruit/Adafruit_nRF52_nrfutil#23]
I'm running window, the dongle is at COM10, using your example I just get Timed out waiting blah blah Says Port not open yet I can see the device COM10 in Device Manager/Ports

**Comment by hathach** [comment]
issues is closed since it got off radar, and lack information to reproduce the issue. Please re-open the issue if it is still your issue. With provided hardware board, BSP version, Arduino IDE version, and sketch that is used to upload.
