### ISSUE TITLE
DfuTransportSerial.ACK_PACKET_TIMEOUT too small for nrf52840 MDK usb dongle

### ISSUE THREAD

**Issue by mtavenrath** [adafruit/Adafruit_nRF52_nrfutil#34]
I've spent quite some time trying to figure out why I was't able to flash a new firmware to my nrf52840 MDK usb dongle.  Besides one random success I've always got the following output

```
C:\temp\nrf52840-mdk>adafruit-nrfutil --verbose dfu serial --package uf2_bootloader-0.2.13-44-gb2b4284-nosd.hex.zip -p com7 -b 115200 --singlebank
Upgrading target on com7 with DFU package C:\temp\nrf52840-mdk\uf2_bootloader-0.2.13-44-gb2b4284-nosd.hex.zip. Flow control is disabled, Single bank, Touch disabled
Opened serial port com7
Starting DFU upgrade of type 2, SoftDevice size: 0, bootloader size: 30336, application size: 0
Sending DFU start packet
Timed out waiting for acknowledgement from device.
Sending DFU init packet

Failed to upgrade target. Error is: Attempting to use a port that is not open
```

It turns out that the ACK_PACKET_TIMEOUT is to small for this device. After increasing this constant to 2.0 I've been able to reliably use this tool to flash new firmware.

https://github.com/adafruit/Adafruit_nRF52_nrfutil/blob/be2e5afb9eee4518489648b09051a1f1d18a1f93/nordicsemi/dfu/dfu_transport_serial.py#L57

**Comment by hathach** [comment]
I have no problem using this tool with various nrf52840 boards. If you think this is a bug, please open one using bug template to provide enough setup/information for reproducing the issue.
