### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDR-Tool** [adafruit/Adafruit_nRF52_nrfutil#39]
Hi, In **Adafruit_nRF52_nrfutil**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
pyserial>=2.7
click>=5.1
ecdsa>=0.13
behave
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **pyserial** can be changed to *>=2.3,<=2.4*.
The version constraint of dependency **click** can be changed to *>=0.7,<=8.1.3*.
The version constraint of dependency **ecdsa** can be changed to *>=0.9,<=0.18.0b2*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the pyserial</summary>
 <pre>serial.Serial
</pre>
</details>
<details><summary>The calling methods from the click</summary>
 <pre>click.echo
click.Path
</pre>
</details>
<details><summary>The calling methods from the ecdsa</summary>
 <pre>ecdsa.SigningKey.from_pem
ecdsa.SigningKey.generate
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>sys.getsizeof
nordicsemi.dfu.util.int32_to_bytes
input
Package.create_zip_package
self.dfu_transport.send_init_packet
self.dfu_transport.open
sd_reqs_value.append
nordicsemi.dfu.dfu.Dfu.command
self.callbacks.keys
self.decode_esc_chars
itertools.chain.from_iterable
hashlib.sha256.update
subprocess.Popen
self.DfuTransportSerial.super.send_init_packet
array.array
logging.error
getattr
signing.Signing
target.stdin.close
nordicsemi.dfu.manifest.ManifestGenerator.generate_manifest
i.chr.upper
IntelHex
Package.calculate_sha256_hash
self.fromdict
shutil.rmtree
datetime.timedelta
self.__create_temp_workspace
end.start.slice.self.segments
self.DfuTransportBle.super.open
serial.Serial.close
math.pow
frames.append
target.kill
ExtendedSegmentAddressRecordError
self.target_db.get_targets
self.nRFHex.super.minaddr
click.echo
behave.when
list
self.DfuTransportSerial.super.is_open
min
self.bootloaderhex.size
self.DfuTransportSerial.super.open
r.update
os.path.isfile
handler
os.environ.items
IntelHex.tofile
setuptools.command.test.test.finalize_options
ord
self.get_last_error
sum.append
input.lower
compat.dict_keys.sort
RecordLengthError
self.dfu_transport.send_firmware
sum.rstrip
compat.StringIO.getvalue
kill_process
command.split
enumerate
random.randint
os.path.exists
self.DfuTransportSerial.super.send_firmware
self.sk.to_pem
nose.run_exit
self.clear_received_response
sum.split
nordicsemi.exceptions.InvalidArgumentException
self.sk.get_verifying_key.verify
i.i.vk_x_str.decode
open.write
ord.append
logging.getLogger.error
vk.to_string.binascii.hexlify.decode
zip
self.find_target
click.testing.CliRunner
TextOrNoneParamType
nordicsemi.exceptions.NordicSemiException
hashlib.sha256
time.sleep
self.serial_port.isOpen
bisect.bisect_right
self.DfuTransportBle.super.send_activate_firmware
len.find
join
EnvTargetDatabase
compat.dict_keys
self.nRFHex.super.tobinfile
self.get_softdevice_variant
TypeError
self.send_control_data
compat.range_l.bytes.upper
args.insert
match.groupdict.lower
Package.calculate_file_size
sizeof
Exception
self.nRFHex.super.__init__
sorted
nordicsemi.dfu.util.slip_encode_esc_chars
logging.getLogger
self.stderr_thread.start
threading.Thread
NordicSemiException
zipfile.ZipFile
total_size
json.dumps
difflib.unified_diff
nordicsemi.dfu.dfu.Dfu.dfu_send_images
sum.upper
os.getcwd
self.close
self.puts
all_handlers.items
msvcrt.setmode
self._dfu_send_image
os.path.basename.replace
os.path.dirname
self.gets
self.DfuTransportSerial.super.__init__
self.loadfile
nordicsemi.exceptions.NotImplementedException
self.DfuTransportBle.super.__init__
hex
init_packet_file.write
open.close
self.get_vk_hex
nRFHex.tobinfile
RecordChecksumError
nRFHex
self.__generate_struct_format_string
prepare_lines
self._read_file
self.serial_port.write
DfuErrorCodeBle.error_code_lookup
firmware_file.read
compat.array_tobytes
StartSegmentAddressRecordError
down
HexRecordError
self.decode_esc_chars.pop
DuplicateStartAddressRecordError
self._buf.get
fclose
traceback.print_exc
click.option
Package.normalize_firmware_to_bin
self.get_erase_wait_time
self._send_event
self.get_vk_pem
BasedIntOrNoneParamType
os.listdir
self.addresses.sort
nordicsemi.__main__.int_as_text_to_int
IntelHex.dump
self.process.stdin.close
compat.range_g
sk_file.read
context.runner.isolated_filesystem
AddressOverlapError
getsizeof.total_size
self._tobinarray_really
self.sk.get_verifying_key
fwrite
self.targets.append
compat.dict_items_g
context.application.split
self.dfu_transport.send_validate_firmware
int_as_text_to_int
self.sk.to_pem.decode
dikt.keys
nordicsemi.dfu.dfu_transport_serial.DfuTransportSerial.register_events_callback
behave.then
sd_req.lower
nordicsemi.dfu.dfu_transport_serial.DfuTransportSerial
compat.range_l
self.DfuTransportBle.super.send_firmware
nordicsemi.dfu.crc16.calc_crc16
self.SoftdeviceBootloaderFirmware.super.__init__
self.dfu_transport.send_start_dfu
HciPacket
Manifest
self.dfu_transport.is_open
Firmware
i.i.vk_y_str.decode
self.__add_firmware_info
struct.pack
self._start_dfu
Package._is_bootloader_softdevice_combination
tofile.write
reprlib.repr
ecdsa.SigningKey.generate
self.sk.get_verifying_key.to_string
IntelHex.loadbin
self.loadbin
bytearray
click.argument
signing.Signing.load_key
nordicsemi.exceptions.IllegalStateException
callback
sum
dikt.items
re.match
self._wait_for_condition
array.array.append
source._buf.copy
os.path.abspath
self.dfu_transport.close
IntelHexError
os.environ.get
re.match.groupdict
id
self.serial_port.close
set.add
compat.asbytes
self._get_start_end
Packet
expected_zip_content.append
self.firmwares_data.pop
BadAccess16bit
uart_buffer.count
self.send_packet_data
source.start_addr.copy
self.DfuTransportSerial.super.close
result.output.find
list.append
init_packet_data.copy
_DeprecatedParam
bytes
f.read
nordicsemi.dfu.manifest.ManifestGenerator
setattr
nordicsemi.dfu.package.Package
self.get_mbr_end_address
f_fileno
self.send_packet
self.sk.sign
endings.append
ecdsa.SigningKey.from_pem
self.loadhex
binascii.unhexlify
nordicsemi.dfu.util.query_func
code_lookup.get
str
nordicsemi.dfu.package.Package.unpack_package
nRFHex.size
ThreeWireUartPacket
self.dfu_transport.register_events_callback
_force_stream_binary
self.is_open
InvalidStartAddressValueError
float
self.dfu_transport.send_activate_firmware
self.target_db.get_target
result.extend
compat.dict_keys_g
context.args.extend
self._create_init_packet
all_handlers.update
click.Path
args.extend
context.bootloader.split
ValueError
format
Package.calculate_crc16
os.path.basename
slice
range
compat.StringIO
dikt.copy
s.encode
source.endswith
json.loads
condition_function
up
bin.array_tobytes.hexlify.asstr.upper
sio.getvalue.splitlines
assert_init_packet_data
ascii_hex_to_int
self.DfuTransportBle.super.is_open
self.get_targets
iter
self.sk.get_verifying_key.to_pem
sd_req.split
error_message.format.format
result.append
is_timeout
self.bootloaderhex.tobinfile
super
distutils.core.setup
self.address_has_magic_number
divmod
tempfile.mkdtemp
RecordTypeError
nordicsemi.dfu.signing.Signing
self.set_waiting_for_notification
setuptools.find_packages
dict
d.items
isinstance
o.decode
self.serial_port.read
str.lower
self.size
sd_reqs.split.split
logging.basicConfig
decode
self.sk.to_string
context.target_registry.get_all
type
StartLinearAddressRecordError
xrange
self.stdout_thread.start
self.get_vk_code
binascii.hexlify
context.runner.invoke
nRFHex.bootloadersize
max
fread
package.write
self.process.poll
self._buf.update
int
self._removeuicr
nordicsemi.dfu.manifest.Manifest.from_json
logging.getLogger.info
self.fail
queue.Queue
sys.exc_info
manifest_file.write
len
binary_file.read
data.pop
EOFRecordError
IntelHex.__init__
RuntimeError
json.load
self.create_manifest
self.tobinfile
self._buf.pop
calc_crc16
nordicsemi.dfu.package.Package.generate_package
self.minaddr
IntelHex._get_eol_textfile
nordicsemi.dfu.signing.Signing.load_key
context.softdevice.split
SoftdeviceBootloaderFirmware
sk_file.write
InitPacketData
data.append
self.get_ack_nr
progress_percentage
pkg.infolist
self.process.kill
struct.unpack
nordicsemi.dfu.model.FirmwareKeys.BIN_FILENAME.firmware.replace
self.addresses
IntelHex.tobinfile
ExtendedLinearAddressRecordError
self.init_packet_fields.keys
sum.get
self.serial_port.setDTR
MissingArgumentException
_try
event_type.self.callbacks.append
self.frombytes
compat.asstr
os.path.isdir
beginnings.insert
nordicsemi.dfu.util.slip_parts_to_four_bytes
self.sk.to_string.hex
s.decode
nordicsemi.dfu.signing.Signing.gen_key
set
self.DfuTransportSerial.super.send_start_dfu
map
click.group
os.path.join
IllegalStateException
staticmethod
os.path.getsize
self.DfuTransportBle.super.close
self.DfuTransportBle.super.send_start_dfu
sd_reqs.append
cli
nordicsemi.dfu.dfu.Dfu
signing.Signing.sign
event_type.self.callbacks.remove
self.write_hex_file
Record._from_bytes
nordicsemi.dfu.signing.Signing.get_vk
self.start_addr.get
self.DfuTransportBle.super.send_init_packet
self.open
remove_none_entries
logging.getLogger.debug
Packet.generate_packet
queue.put
serial.Serial
NotEnoughDataError
open
nRFException
common_steps.get_resources_path
self.DfuTransportSerial.super.send_activate_firmware
nordicsemi.dfu.dfu_transport.DfuTransport.create_image_size_packet
time.time
pipe.close
self.to_json
cli.command
self.DfuTransportSerial.super.send_validate_firmware
cli.group
self.DfuTransportBle.super.send_validate_firmware
pkg.extractall
args.append
self.dfu_transport.get_activate_wait_time
nordicsemi.dfu.util.int16_to_bytes
print
behave.given
bin.array_tobytes.hexlify.translate
repr
self._wait_while_opening_transport
self.maxaddr
hashlib.sha256.digest
IntelHex.minaddr
datetime.datetime.now
self._tobinstr_really
chr
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by tekktrik** [comment]
I don't think a change like this makes sense for our project or needs.  Thanks for offering though!
